### PR TITLE
Default heartbeat on

### LINKED ISSUE #13: Switch to asynchronous consumer for long running stability
More details here: https://github.com/Duke-GCB/bespin-mailer/issues/1

Asynchronous consumer documentation:
http://pika.readthedocs.io/en/0.11.2/examples/asynchronous_consumer_example.html

### PR DESCRIPTION
**Pull request by johnbradley**
Fixes #13 
Turns heartbeat back on to keep long polling connections alive. (The `None` value lets the rabbitmq instance determine a good heartbeat value).
The lando worker processor will now run in a disconnected manner while handling a message. 
This will avoid the disconnection errors that occur for long running jobs and the reason heartbeat was disabled.

Also includes changes to get the circleci integration tests working again (I think this was due to changes within circleci). Integration tests require a rabbitmq instance to be running.

### CODE REVIEW

**Review by dleehr — COMMENTED** [review]
I like the solution that the client disconnects from the queue. It lets the RabbitMQ server do what it's good at and simplifies our code.

I do think the implementation raises some questions though about how to use a `MessageRouter`

When it doesn't disconnect, a `MessageRouter` would loop forever and process messages - meaning that applications using it could instantiate one and be done.
 But as far as I can tell, a disconnecting `MessageRouter` handles a single message, disconnects, and is no longer usable.

So the questions I have are

1. Is that assumption (that a disconnecting MessageRouter instance only handles one message) correct? 
2. How should an application manage the lifecycle of a `MessageRouter` in either mode?
3. What constitutes a "long running job"? 
4. What happens if a non-disconnecting `MessageRouter` is used with a "long running job"? Is there a more graceful failure than before?

Assuming a disconnecting `MessageRouter` behaves this way, I suggest it would be better expressed as a distinct class (e.g. `DisconnectingMessageRouter` and `LoopingMessageRouter` vs a single `MessageRouter` class that significantly changes its behavior based on a boolean).

**Comment by johnbradley** [comment]
The `MessageRouter` loops in either case. In one it keeps the connection open. In the other it disconnects while servicing a message.

This method loops forever (or an event handler closes the connection):
https://github.com/Duke-GCB/lando-messaging/blob/74268b4d654e63ea39ac0834492140b8a7933ef4/lando_messaging/workqueue.py#L250-L255

This method also loops forever (or until `self.receiving_messages` is false.
https://github.com/Duke-GCB/lando-messaging/blob/74268b4d654e63ea39ac0834492140b8a7933ef4/lando_messaging/workqueue.py#L269-L273
Perhaps this should be renamed `_process_messages_loop_with_disconnect`.

**Comment by dleehr** [comment]
Thanks, I do see that it loops and the only place `self.receiving_messages` would be set to `False` is in `shutdown()`, but that raises a question: How does `shutdown()` get called - is that only used in the tests?

I still don't see how the client would re-connect to the queue after disconnecting. Is there a test for this behavior?

**Comment by johnbradley** [comment]
### Summary from conversation with @dleehr yesterday.

The `MessageRouter` sets up a `WorkQueueProcessor` that is appropriate for __lando__ or __lando worker__.
The standard `WorkQueueProcessor` receives messages using the pika looping method and must finish processing a message within the heartbeat timeout (default pika library behavior). The WorkQueueProcessor stays connected to AMQP the entire time.
The `DisconnectingWorkQueueProcessor` receives messages but disconnects while processing the messages. 
Both `WorkQueueProcessor` and `DisconnectingWorkQueueProcessor` will loop and keep processing messages until the `shutdown` method is called.

> What constitutes a "long running job"?

If a message takes longer than the heartbeat timeout amount. The default is 60 seconds

> What happens if a non-disconnecting MessageRouter is used with a "long running job"? Is there a more graceful failure than before?

If `WorkQueueProcessor` takes too long the pika library will raise an exception once the message processing completes. With our deployment setup docker would restart __lando__ if this occurred so users jobs would continue as normally.

**Comment by johnbradley** [comment]
> I still don't see how the client would re-connect to the queue after disconnecting. Is there a test for this behavior?

The `DisconnectingWorkQueueProcessor` automatically connects when it waits for the next message. This is existing functionality of the `receive_loop_with_callback method`.
https://github.com/Duke-GCB/lando-messaging/blob/7d42270f9fbfb55753400a1373f01825a8de714f/lando_messaging/workqueue.py#L116-L127

**Review by dleehr — APPROVED** [review]

**Pull request merged**
